---
title: "Sensor Reading Code"
format: html
---

## Set Up
```{r}
# Required packages to run script. If not on computer download and install.
library(ggplot2)
library(lubridate)
library(reshape2)
library(data.table)
library(dplyr)
library(gridExtra)
library(zoo)
library(plotly)
library(gridExtra)
library(data.table)
library(slider)
library(tidyverse)
```


## Code

```{r}
#Code from Campbell sci to keep header, remove NANs, convert timestamp to correct format, and add column for file name as ID, 
importCSdata <- function(filename,RetOpt="data"){
  if(RetOpt=="info"){
    # bring in entire header of CSI TOA5 data file for metadata
    stn.info <- scan(file=filename,nlines=4,what=character(),sep="\r")
    return(stn.info)
  } else {
    # second line of header contains variable names
    header <- scan(file=filename,skip=1,nlines=1,what=character(),sep=",")
    # bring in data
    stn.data <- read.table(file=filename,skip=4,header=FALSE, na.strings=c("NAN"),sep=",")
    names(stn.data) <- header
    # add column of R-formatted date/timestamps
    stn.data$TIMESTAMP <- as.POSIXct(strptime(stn.data$TIMESTAMP,format="%Y-%m-%d %H:%M", tz="us/pacific"))
    stn.data$ID<-basename(filename)
    return(stn.data)}}
```


```{r}
#set working directory
setwd("C:/Users/emmam/Downloads/senior thesis/DataForWorking")
```


```{r}
# import all .dat files within folder
filenames=list.files(path=getwd(),pattern="[.]dat", recursive=T)

# bring in the files in a list using the Campbell function
list <- lapply(filenames, importCSdata)

#Combine all files in the list into a data frame. Select fill=T to merge files with different column numbers
data <-rbindlist(list, fill = TRUE)

#convert to data table
data <- data.table(data)

# Remove duplicates from data.
data <- data[!duplicated(data),]

#Order file based on timestamp
data<-data[order(TIMESTAMP),]
```


```{r}
# ##SoilVUE
# #Select columns for SoilVUE
# soilvue<-cbind(data[,c(1,69:193)])

##SoilVUE
#Select columns for SoilVUE
SVburnt<-cbind(data[,c(1,69:356)])

#This will make it so there's only ONE column for temp, as opposed to various columns (goes from wide to long table format). Keep information that is pertinent to identify temp like timestamp and PP
sv <- SVburnt %>%
  melt(id.vars=c( "TIMESTAMP"), value.name="num")

sv=data.table(sv)


#Breakup variable name so we can extract plot and sensor info
sv[, c("rest", "plot","depth","avg"):= tstrsplit(variable, "_", fixed=TRUE)]
sv$rest<-NULL

#assign similar column names as above
```


```{r}
#Paired plot info

sv[, PP := as.character(NA)]

# Assign paired plot (PP) values based on 'plot' column
sv[, PP := fifelse(plot == "BH1" | plot == "BC1", "1", PP)]
sv[, PP := fifelse(plot == "BH2" | plot == "BC2", "2", PP)]
sv[, PP := fifelse(plot == "BH3" | plot == "BC3", "3", PP)]
sv[, PP := fifelse(plot == "BH4" | plot == "BC4", "4", PP)]

# Map NB plots to their PP values
sv[, PP := fifelse(plot == "NB1", "5", PP)]
sv[, PP := fifelse(plot == "NB2", "6", PP)]
sv[, PP := fifelse(plot == "NB3", "7", PP)]
sv[, PP := fifelse(plot == "NB4", "8", PP)]

```


```{r}
# sv$PP<-NA
# sv[, PP := ifelse(plot=="BH1"|plot=="BC1", "1", PP)]
# sv[, PP := ifelse(plot=="BH2"|plot=="BC2", "2", PP)]
# sv[, PP := ifelse(plot=="BH3"|plot=="BC3", "3", PP)]
# sv[, PP := ifelse(plot=="BH4"|plot=="BC4", "4", PP)]
# 
# 
# # Map NB plots to their PP values
# sv[, PP := fifelse(plot == "NB1", "5", PP)]
# sv[, PP := fifelse(plot == "NB2", "6", PP)]
# sv[, PP := fifelse(plot == "NB3", "7", PP)]
# sv[, PP := fifelse(plot == "NB4", "8", PP)]
```


```{r}
#assign trt
sv$trt<-NA
sv[, trt := ifelse(plot=="BH1"|plot=="BH2"|plot=="BH3"|plot=="BH4", "H", trt)]
sv[, trt := ifelse(plot=="BC1"|plot=="BC2"|plot=="BC3"|plot=="BC4", "C", trt)]
sv[, trt := ifelse(plot=="NB1"|plot=="NB2"|plot=="NB3"|plot=="NB4", "H", trt)]

```


```{r}
#assign measurement type
sv$measurement<-NA
sv[, measurement := ifelse(avg=="Avg(1)", "moisture", measurement)]
sv[, measurement := ifelse(avg=="Avg(2)", "permitivity", measurement)]
sv[, measurement := ifelse(avg=="Avg(3)", "temp", measurement)]
sv[, measurement := ifelse(avg=="Avg(4)", "EC", measurement)]
```


```{r}
# #Extract date from TIMESTAMP (this will make it easier to graph than TIMESTAMP, also so you can use it for daily average)
# sv$date<-as.Date(sv$TIMESTAMP)

#subset temp
temp.sv<- subset(sv, measurement=="temp")

#Remove instrument noise
temp.sv[, num := ifelse(num<(-5), NA, num)]
temp.sv[, num := ifelse(num>40, NA, num)]

temp.sv$PP<- as.numeric(temp.sv$PP)
#temp.sv$depth<- as.numeric(temp.sv$depth)

#unique(temp.sv$depth)
temp.sv$depth <- factor(temp.sv$depth, labels=c("5", "10", "20","30", "40","50"))

temp.sv$trt <- factor(temp.sv$trt,levels = c("H", "C"))

temp.sv <- temp.sv %>% filter(!is.na(num) & !is.na(depth) & !is.na(trt) & !is.na(PP))

```


```{r}
# Filter for H and C treatments separately
t_h_sv <- temp.sv %>% filter(trt == "H")
t_c_sv <- temp.sv %>% filter(trt == "C")

# Join H and C datasets based on TIMESTAMP, depth, and PP
t_diff_sv <- t_h_sv %>%
  inner_join(t_c_sv, by = c("TIMESTAMP", "depth", "PP")) %>%
  mutate(diff_H_C = num.x - num.y) %>%  # Calculate differences for each depth
  select(TIMESTAMP, depth, PP, diff_H_C)  # Select relevant column

temp_filtered_Burned <- temp.sv %>% filter(PP %in% 1:4)

temp_filtered_Unburned <- temp.sv %>% filter(PP %in% 5:8)
```


```{r}
# KEEP
#Raw Temp data SoilVUE
ggplot(temp_filtered_Burned, aes(x = TIMESTAMP, y = num, color = trt)) +
  geom_point(shape = 16, size = 1) + 
  ylab(expression("Temperature (degree*C)")) +
  xlab("Date") +
  theme_bw() +
  theme(
    legend.text = element_text(size=14),
    axis.text.x = element_text(size= 14, angle = 90, vjust = 0.5),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size=14),  # Increase x-axis label font size
    axis.title.y = element_text(size=14),  # Increase y-axis label font size
    strip.text = element_text(size = 12, color = "black", face = "italic"),
    legend.title = element_blank()  # Remove legend title
  ) +
  guides(color = guide_legend(title = FALSE)) +  # Remove legend title
  facet_grid(PP ~ depth) +
  ggtitle("SoilVUE Paired Burned Plots 1-4") +
  scale_color_manual(values = c("red","blue"))

```


```{r}
#Raw Temp data SoilVUE
ggplot(temp_filtered_Unburned, aes(x = TIMESTAMP, y = num, color = trt)) +
  geom_point(shape = 16, size = 1) + 
  ylab(expression("Temperature (degree*C)")) +
  xlab("Date") +
  theme_bw() +
  theme(
    legend.text = element_text(size=14),
    axis.text.x = element_text(size= 14, angle = 90, vjust = 0.5),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size=14),  # Increase x-axis label font size
    axis.title.y = element_text(size=14),  # Increase y-axis label font size
    strip.text = element_text(size = 12, color = "black", face = "italic"),
    legend.title = element_blank()  # Remove legend title
  ) +
  guides(color = guide_legend(title = FALSE)) +  # Remove legend title
  facet_grid(PP ~ depth) +
  ggtitle("SoilVUE Controlled Temperature Unburned Plots 1-4") +
  scale_color_manual(values = c("red","blue"))
  #ggsave("C:/Program Files/RStudio/Tilden Park Warming/Graphs/SoilVUE Controlled Temperature Unburned Plots 1-4.jpg", width=15,height=10)
# ggsave("C:/Program Files/RStudio/Task 5 Microwarming/Plots/Research Paper/SoilVUE Controlled and Heated Temperature Plots 1-3.jpg", width=15, height=10)
```


```{r}
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
  return(data_sum)
}
```


```{r}
# temp.sv$PP<- as.factor(temp.sv$PP)

#temp.sv$depth <-factor(temp.sv$depth,levels = c("5 cm", "10 cm", "20 cm","30 cm", "40 cm", "50 cm"),ordered = TRUE)


#Original 
# summary.sv <- temp.sv %>%
#  dplyr::group_by(TIMESTAMP,depth, trt, PP) %>%
#  dplyr::summarise(
#   N=length(num),
#   mean= mean(num, na.rm=T),
#   sd=sd(num, na.rm=T),
#   se=sd(num, na.rm=T)/sqrt(sum(!is.na(num))))


# Convert TIMESTAMP to datetime if it's not already
temp.sv$TIMESTAMP <- as.POSIXct(temp.sv$TIMESTAMP)

# Ensure depth, trt, and PP are factors if they are categorical
temp.sv$depth <- as.factor(temp.sv$depth)
temp.sv$trt <- as.factor(temp.sv$trt)
temp.sv$PP <- as.factor(temp.sv$PP)

```


```{r}
# Step 1: Calculate summary statistics for each group
summary_sv <- temp.sv %>%
  dplyr::group_by(TIMESTAMP, depth, trt, PP) %>%
  dplyr::summarise(
    num = mean(num, na.rm = TRUE),  # Calculate mean of 'num' within each group
  )


# Step 2: Calculate overall mean, sd, and se values per group (TIMESTAMP, depth, trt)
summary_final_sv <- summary_sv %>%
  dplyr::group_by(TIMESTAMP, depth, trt) %>%
  dplyr::summarise(
    mean = mean(num, na.rm = TRUE),  # Calculate mean of 'mean' within each group
    sd = sd(num, na.rm = TRUE),      # Calculate sd of 'num' within each group
    se = sd(num, na.rm = TRUE) / sqrt(sum(!is.na(num)))  # Calculate se of 'num' within each group
  )

summary_final_sv |>
    filter(mean == 0) |>
    arrange(TIMESTAMP)

```

At 2024-11-12 at 15:00, mean values turned to becoming 0. 

```{r}
#KEEP
#standard deviation all depths
ggplot(summary_final_sv, aes(x = TIMESTAMP, y = mean, colour = trt)) +
  geom_point(size = 0.5) +
  geom_ribbon(aes(ymin = mean - sd, ymax = mean + sd, fill = trt), alpha = 0.5, colour = NA) +
  scale_color_manual(values = c("C" = "blue", "H" = "red")) +
  scale_fill_manual(values = c("C" = "blue", "H" = "red")) +
  ylab("Mean Temp (degree*C)") +
  xlab("Date") +
  theme_bw() +
  theme(
    legend.text = element_text(size=14),
    axis.text.x = element_text(size= 14),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size=14),  # Increase x-axis label font size
    axis.title.y = element_text(size=14),# Increase y-axis label font size
    strip.text = element_text(size = 12, color = "black", face = "italic")
  ) +
  facet_grid(~depth) +
  ggtitle("SoilVUE Mean Temperature & Standard Deviation Plots 1-3") +
  scale_x_datetime(breaks = "8 days", date_labels = "%b-%d") +
  theme(axis.text.x = element_text(angle = -45)) +
  labs(color = NULL, fill = NULL)
# ggsave("C:/Program Files/RStudio/Task 5 Microwarming/Plots/SoilVUE Mean Temperature Standard Deviation Plots 1-3.pdf", width=15, height=10)
  # ggsave("C:/Program Files/RStudio/Task 5 Microwarming/Plots/Research Paper/SoilVUE Mean Temperature & Standard Deviation Plots 1-3.jpg", width=15, height=10)


```


```{r}
#standard deviation plots 30 cm depth
summary_final_sv_30cm <- subset(summary_final_sv, depth == '30')

ggplot(summary_final_sv_30cm, aes(x = TIMESTAMP, y = mean, colour = trt)) +
  geom_point(size = 0.5) +
  geom_ribbon(aes(ymin = mean - sd, ymax = mean + sd, fill = trt), alpha = 0.5, colour = NA) +
  scale_color_manual(values = c("C" = "blue", "H" = "red")) +
  scale_fill_manual(values = c("C" = "blue", "H" = "red")) +
  ylab("Temperature (degree*C)") +
  xlab("Date") +
  theme_bw() +
  theme(
    legend.text = element_text(size=14),
    axis.text.x = element_text(size= 14),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size=14),  # Increase x-axis label font size
    axis.title.y = element_text(size=14),# Increase y-axis label font size
    strip.text = element_text(size = 12, color = "black", face = "italic")
  ) +
  ggtitle("SoilVUE Temperature Standard Deviation Plot for 30 cm Depth") +
  scale_x_datetime(breaks = "8 days", date_labels = "%b-%d") +
  theme(axis.text.x = element_text(angle = -45)) +
  labs(color = NULL, fill = NULL)
# ggsave("C:/Program Files/RStudio/Task 5 Microwarming/Plots/SoilVUE Temperature Standard Deviation Plot for 30cm Depth.pdf", width=10, height=5)
# ggsave("C:/Program Files/RStudio/Task 5 Microwarming/Plots/SoilVUE Temperature Standard Deviation Plot for 30cm Depth.jpg", width=10, height=5)
```


```{r}
# the following line of code provides the difference plots for GMF and SC
t_diff_gmf2 <- t_diff_gmf %>%
  mutate(distance = 10)
t_diff_gmf2$PP <- as.numeric(as.character(t_diff_gmf2$PP))
t_diff_gmf2 <- t_diff_gmf2 %>%
  mutate(PP = case_when(
    PP == 1 ~ 4,
    PP == 2 ~ 5,
    PP == 3 ~ 6,
    TRUE ~ PP
  ))
t_diff_gmf2$PP <- as.factor(t_diff_gmf2$PP)
t_diff_gmf2 <- t_diff_gmf2[!is.na(t_diff_gmf2$diff), ]
t_diff_gmf2$depth <- as.character(t_diff_gmf2$depth)


t_diff_sv2 <- t_diff_sv %>%
  mutate(distance = 16.5)
t_diff_sv2$depth <- as.character(t_diff_sv2$depth)


t.trt.diff_sv_gmf <- rbind(t_diff_sv2, t_diff_gmf2)
t.trt.diff_sv_gmf$TIMESTAMP <- as.POSIXct(t.trt.diff_sv_gmf$TIMESTAMP, format = "%Y-%m-%d %H:%M:%S")
t.trt.diff_sv_gmf <- t.trt.diff_sv_gmf %>%
  arrange(TIMESTAMP) %>%
  group_by(TIMESTAMP) %>%
  arrange(match(depth, c("5", "10", "20", "30", "40", "50")))  # Specify the depths in the desired order
t.trt.diff_sv_gmf$depth <- factor(t.trt.diff_sv_gmf$depth, levels = c("5", "10", "20", "30", "40", "50"))


palette1 <- c("turquoise3", "steelblue", "navy", "lightgreen", "greenyellow", "green4")

```


```{r}
# Separate SoilVUE and GMF datasets
soilvue_data <- subset(t.trt.diff_sv_gmf, PP %in% c(1, 2, 3))
gmf_data <- subset(t.trt.diff_sv_gmf, PP %in% c(4, 5, 6))

# SoilVUE and GMF Temp Diff
# Separate SoilVUE and GMF datasets
soilvue_data <- subset(t.trt.diff_sv_gmf, PP %in% c(1, 2, 3))
gmf_data <- subset(t.trt.diff_sv_gmf, PP %in% c(4, 5, 6))



#Keep
# SoilVUE and GMF Temp Diff
ggplot() +
  geom_point(data = soilvue_data, aes(x = TIMESTAMP, y = diff_H_C, colour = as.factor(PP)), shape = 1, size = 0.5) +
  scale_color_manual(name = "SoilVUE", values = palette1[1:3]) +  # Use the first three colors from the palette
  guides(colour = guide_legend(override.aes = list(size = 4, shape = 16))) +  # Increase dot size and make solid in the legend
  new_scale_color() +
  geom_point(data = gmf_data, aes(x = TIMESTAMP, y = diff_H_C, colour = as.factor(PP)), shape = 1, size = 0.5) +
  scale_color_manual(name = "GMF", values = palette1[4:6]) +  # Use the last three colors from the palette
  guides(colour = guide_legend(override.aes = list(size = 4, shape = 16))) +  # Increase dot size and make solid in the legend
  labs(
    x = NULL,
    y = expression(Delta * "Soil Temperature " (degree*C)),
    title = "SoilVUE & GMF Temperature Difference Plots 1-3"
  ) +
  scale_y_continuous(breaks = c(0, 2, 4)) +
  scale_x_datetime(breaks = "8 days", date_labels = "%b-%d") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold", vjust = 1),
    axis.title = element_text(size = 16),
    axis.text.x = element_text(size = 12, angle = -45),
    axis.text.y = element_text(size = 14, hjust = 0.5),
    axis.line = element_line(colour = "black", size = 0.2),
    panel.spacing.y = unit(0, "lines"),
    panel.border = element_rect(color = "black", fill = NA, size = 0.5),
    strip.background = element_rect(fill = "white", colour = "black"),
    strip.text = element_text(size = 16, face = "bold")
  ) +
  geom_hline(yintercept = c(1, 2, 3, 4)) +  # Remove colour argument here
  facet_grid(~depth)
# ggsave("C:/Program Files/RStudio/Task 5 Microwarming/Plots/Research Paper/SoilVUE & GMF Temperature Difference Plots 1-3.pdf", width=6,height=3)
  # ggsave("C:/Program Files/RStudio/Task 5 Microwarming/Plots/Research Paper/SoilVUE & GMF Temperature Difference Plots 1-3.jpg", width=15, height=10)

```


```{r}
#SoilVUE Moisture
moisture.sv<- subset(sv, measurement=="moisture")


moisture.sv$PP<- as.numeric(moisture.sv$PP)

unique(moisture.sv$depth)
moisture.sv$depth <- factor(moisture.sv$depth, labels=c("5 cm", "10 cm", "20 cm","30 cm", "40 cm","50 cm"))


#Keep
# moisture H and C (raw)
ggplot(moisture.sv, aes(x=TIMESTAMP, y=num, colour=trt)) +
  geom_point(shape=16, size=1) + 
  ylab(expression("Moisture Content")) +
  xlab("Date") +
  scale_color_manual(values = c("C" = "blue", "H" = "red")) +
  ggtitle("SoilVUE Moisture Plots 1-4") +
  theme_bw() +
  theme(
    legend.text = element_text(size=14),
    axis.text.x = element_text(size= 14, angle = -45, vjust = 0.5),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size=14),  # Increase x-axis label font size
    axis.title.y = element_text(size=14),# Increase y-axis label font size
    strip.text = element_text(size = 12, color = "black", face = "italic")
  ) +
  guides(colour = guide_legend(title = NULL)) +
  facet_grid(PP~depth)
  ggsave("C:/Program Files/RStudio/Tilden Park Warming/Graphs/SoilVUE Moisture Plots 1-4.jpg", width=15,height=10)
# ggsave("C:/Program Files/RStudio/Task 5 Microwarming/Plots/Research Paper/SoilVUE Moisture Plots 1-3.pdf.jpg", width=15, height=10)
```


```{r}
# Filter the data for PP 3
moisture.sv_PP3 <- subset(moisture.sv, PP == 3)


#Keep 
# Create raw data plot 3
ggplot(moisture.sv_PP3, aes(x=TIMESTAMP, y=num, colour=trt)) +
  geom_point(shape=5, size=0.5) + 
  ylab(expression("Moisture Content")) +
  xlab("Date") +
  scale_color_manual(values = c("C" = "blue", "H" = "red")) +
  #  scale_x_datetime(
  #   date_breaks = "10 days",       # Set break intervals to 20 days
  #    date_labels = "%d %b"       # Format the date labels
  # ) +
  ggtitle("SoilVUE Moisture Plot 3") +
  theme_bw() +
  theme(
    legend.text = element_text(size=14),
    axis.text.x = element_text(size= 12, angle = -45, vjust = 0.5),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size=14),  # Increase x-axis label font size
    axis.title.y = element_text(size=14),# Increase y-axis label font size
    strip.text = element_text(size = 12, color = "black", face = "italic")
  ) +
  guides(colour = guide_legend(title = NULL)) +
  facet_grid(. ~ depth)
# ggsave("C:/Program Files/RStudio/Task 5 Microwarming/Plots/SoilVUE Moisture Plot 3.pdf", width=10, height=5)
# ggsave("C:/Program Files/RStudio/Task 5 Microwarming/Plots/SoilVUE Moisture Plot 3.jpg", width=10, height=5)

```


```{r}
moisture_num <- moisture.sv$num

names(temp.sv) <- c("TIMESTAMP", "variable", "temp_num", "plot", "depth", "avg", "PP", "trt", "measurement")

temp_moisture_sv <- cbind(temp.sv, moisture_num = moisture.sv$num)


#Keep 
# Temp vs moisture 
ggplot(temp_moisture_sv, aes(x = temp_num, y = moisture_num, colour = trt)) +
  geom_point(shape = 1, size = 0.75) +
  ylab(expression("Soil Moisture")) +
  xlab("Temperature (degree*C)") +
  labs(title = "SoilVUE Temperature vs Moisture Plots 1-3") +
  theme_bw() +
  facet_grid(PP ~ depth) +
  scale_color_manual(values = c("C" = "blue", "H" = "red"))
# ggsave("C:/Program Files/RStudio/Task 5 Microwarming/Plots/SoilVUE Temperature vs Moisture Plots 1-3.pdf", width=15,height=10,dpi=300)
```


```{r}
summary.moisture2 <- moisture.sv %>%
  dplyr::group_by(TIMESTAMP,depth, trt) %>%
  dplyr::summarise(
    N=length(num),
    mean= mean(num, na.rm=T),
    sd=sd(num, na.rm=T),
    se=sd(num, na.rm=T)/sqrt(sum(!is.na(num))))


#KEEP
#standard deviation moisture 
ggplot(summary.moisture2, aes(x = TIMESTAMP, y = mean, colour = trt)) +
  geom_point(size = 1) +
  geom_ribbon(aes(ymin = mean - sd, ymax = mean + sd, fill = trt), alpha = 0.5, colour = NA) +
  scale_color_manual(values = c("C" = "blue", "H" = "red")) +
  scale_fill_manual(values = c("C" = "blue", "H" = "red")) +
  ylab("Moisture Content") +
  xlab("Date") +
  theme_bw() +
  theme(
    legend.text = element_text(size=14),
    axis.text.x = element_text(size= 14),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size=14),  # Increase x-axis label font size
    axis.title.y = element_text(size=14),# Increase y-axis label font size
    strip.text = element_text(size = 12, color = "black", face = "italic")
  ) +
  facet_grid(~depth) +
  ggtitle("SoilVUE Moisture Mean & Standard Deviation Plots 1-3") +
  scale_x_datetime(breaks = "8 days", date_labels = "%b-%d") +
  theme(axis.text.x = element_text(angle = -45)) +
  labs(color = NULL, fill = NULL)
# ggsave("C:/Program Files/RStudio/Task 5 Microwarming/Plots/SoilVUE Moisture Standard Deviation Plots 1-3.pdf", width=15, height=10)
  # ggsave("C:/Program Files/RStudio/Task 5 Microwarming/Plots/Research Paper/SoilVUE Moisture Standard Deviation Plots 1-3.jpg", width=15, height=10)



#SoilVUE Electrical Conductivity
EC.sv<- subset(sv, measurement=="EC")


EC.sv$PP<- as.numeric(EC.sv$PP)

unique(EC.sv$depth)
EC.sv$depth <- factor(EC.sv$depth, labels=c("5 cm", "10 cm", "20 cm","30 cm", "40 cm","50 cm"))


#KEEP
# EC H and C (raw)
ggplot(EC.sv, aes(x=TIMESTAMP, y=num, colour=trt)) +
  geom_point(size=0.5) + 
  ylab(expression("Electrical Conductivity (dS/m)")) +
  xlab("Date") +
  scale_color_manual(values = c("C" = "blue", "H" = "red")) +
  scale_x_datetime(
    date_breaks = "20 days",       # Set break intervals to 20 days
    date_labels = "%d %b"       # Format the date labels
  ) +
  ggtitle("SoilVUE Electrical Conductivity Plots 1-3") +
  theme_bw() +
  theme(
    legend.text = element_text(size=14),
    axis.text.x = element_text(size= 14),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size=14),  # Increase x-axis label font size
    axis.title.y = element_text(size=14),# Increase y-axis label font size
    strip.text = element_text(size = 12, color = "black", face = "italic")
  ) +
  guides(colour = guide_legend(title = NULL)) +
  facet_grid(PP~depth)
```


```{r}
summary.EC2 <- EC.sv %>%
  dplyr::group_by(TIMESTAMP,depth, trt) %>%
  dplyr::summarise(
    N=length(num),
    mean= mean(num, na.rm=T),
    sd=sd(num, na.rm=T),
    se=sd(num, na.rm=T)/sqrt(sum(!is.na(num))))


#KEEP
#Standard deviation all depths
ggplot(summary.EC2, aes(x = TIMESTAMP, y = mean, colour = trt)) +
  geom_point(size = 1) +
  geom_ribbon(aes(ymin = mean - sd, ymax = mean + sd, fill = trt), alpha = 0.5, colour = NA) +
  scale_color_manual(values = c("C" = "blue", "H" = "red")) +
  scale_fill_manual(values = c("C" = "blue", "H" = "red")) +
  ylab("Electrical Conductivity (dS/m)") +
  xlab("Date") +
  theme_bw() +
  theme(
    legend.text = element_text(size=14),
    axis.text.x = element_text(size= 14),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size=14),  # Increase x-axis label font size
    axis.title.y = element_text(size=14),# Increase y-axis label font size
    strip.text = element_text(size = 12, color = "black", face = "italic")
  ) +
  facet_grid(~depth) +
  ggtitle("SoilVUE Electrical Conductivity Mean & Standard Deviation Plots 1-3") +
  scale_x_datetime(breaks = "8 days", date_labels = "%b-%d") +
  theme(axis.text.x = element_text(angle = -45)) +
  labs(color = NULL, fill = NULL)
```


```{r}
#SoilVUE Permitivity
PER.sv<- subset(sv, measurement=="permitivity")


PER.sv$PP<- as.numeric(PER.sv$PP)

unique(PER.sv$depth)
PER.sv$depth <- factor(PER.sv$depth, labels=c("5 cm", "10 cm", "20 cm","30 cm", "40 cm","50 cm"))


#KEEP
# EC H and C (raw)
ggplot(PER.sv, aes(x=TIMESTAMP, y=num, colour=trt)) +
  geom_point(size=0.5) + 
  ylab(expression("Permittivity (ɛ)")) +
  xlab("Date") +
  scale_color_manual(values = c("C" = "blue", "H" = "red")) +
  scale_x_datetime(
    date_breaks = "20 days",       # Set break intervals to 20 days
    date_labels = "%d %b"       # Format the date labels
  ) +
  ggtitle("SoilVUE Permittivity Plots 1-3") +
  theme_bw() +
  theme(
    legend.text = element_text(size=14),
    axis.text.x = element_text(size= 14),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size=14),  # Increase x-axis label font size
    axis.title.y = element_text(size=14),# Increase y-axis label font size
    strip.text = element_text(size = 12, color = "black", face = "italic")
  ) +
  guides(colour = guide_legend(title = NULL)) +
  facet_grid(PP~depth)
#  ggsave("C:/Program Files/RStudio/Task 5 Microwarming/Plots/SoilVUE Moisture Plots 1-3.pdf", width=15, height=10)
  ggsave("C:/Program Files/RStudio/Task 5 Microwarming/Plots/Research Paper/SoilVUE Permittivity Plots 1-3.jpg", width=15, height=10)

```